### ISSUE TITLE
Place Group between Project and Description

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#46]
With the new latest version including Groups, you have to re-learn using Cyclone, even if you don't use groups.

Let me explain: Before, the grouping was done over the description, now it's done over the group.

So, if I don't want to group my time slots as I was doing before, I have to enter a Project and a Group name.

Semantically, it makes sense to group by Group, but the order of the text input would make more sense like this: Project, Group, Description. Going from global to detailed.
It's actually like I did in the mock-up of #45 (but instead of Group I wrote Task).

Let's sync if I'm not clear enough 😄

**Comment by Cyclodex** [comment]
> Let me explain: Before, the grouping was done over the description, now it's done over the group.

Correcting: It was only possible to make groups with **Project + Description** ! (still possible)
The new group allows to have any kind of grouping with its own name!

> So, if I don't want to group my time slots as I was doing before, I have to enter a Project and a Group name.

If you don't want to group things, you use **Project + Description**
* If you enter 2 times a project and description the same way, it will make a group still -> kind of backwards compatibility to the once used to the grouping system before.

Yes, we will have to think about "Task" and Group, as I could imagine some other possibility to have "Tasks" which one could priorize if he wants. Then we can simply start tracking on these tasks, so its something close to groups. Its still an idea in my head, but could be worth talking about because we try to plan this next feature here.

**Comment by davidsandoz** [comment]
Sorry, I misunderstood how the new grouping was working. I didn't notice the previous way to group was still working. My bad!
