### ISSUE TITLE
Reduce task block animations

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#55]
Currently, any change made to a task block makes it animate out and in.

It would be expected to have the animation only when the block change section (Open, Done)

@Cyclodex You are probably already aware of that. I just create a ticket so that there is one 🙂

**Comment by Cyclodex** [comment]
Yes, that's actuallly a Bastard one, because a change on the task is recalculating the entries and there for fires the animation on the ng-repeat. 
I kind of like the Animation for the checke, create etc sattes, but yes this happening on renaming a Task/project is Bad.
I am unsure yet how i could solche this but I might be able to solve this later once... :/

**Comment by davidsandoz** [comment]
Thanks for the clarification!

I think the priority should be given to usability over a nice UI.

If one want to edit the task name and then type of task, currently the usability is bad because one have to wait for the animation to happen in between.

IMHO in this case, if we have to choose only between animation for every change or no animation at all, we should go for no animation.

**Comment by Cyclodex** [comment]
I have an idea how i could solve this issue, give me some time :)

**Comment by Cyclodex** [comment]
Improved, but still some random edge cases where it still happens.
But definitely improved, will deploy when test tomorrow is good enough.
