### ISSUE TITLE
Fix the glitch with tasks getting out of sync when modifying one of the entries

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#57]
@davidsandoz Can you please open the **development tools** and check what the output in "console" tells you when you change an entry? (which was not changing your entry in task)

I tested here with chrome and FF and could strangely not reproduce your behaviour. Some plugins which interfere? :-/

**Comment by davidsandoz** [comment]
No errors in the console.

When I updated the project and when I updated the type, the same message is logged in the console:

    Entry (update Group) entry saved with index-KtAwX7xko2wJaJgQT5M

I also tried in private mode so that I have no plugin enabled, but there the app doesn't load after login because it crashes as it is not allowed to load Google Analytics.

    The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.
    Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.
    wants to go somewhere now... why? 
    ###################### 
    trans $to === today

This could be a separate issue to fix.

But then I tried to log in with Chrome Canary (where I don't have any plugin), but after login the app doesn't load neither. However, the Google Analytics errors are not showing up, only what comes after:

    wants to go somewhere now... why? 
    ###################### 
    trans $to === today

I hope this can help 🙂

**Comment by Cyclodex** [comment]
I don't get this, I have no issues also not in private mode. Might need some investigations together.
There is now a new release also, but I don't think this will change anything for you.
Sorry - not being able to reproduce is making things harder :(

**Comment by davidsandoz** [comment]
I couldn't reproduce myself. Let's close it then.

**Comment by Cyclodex** [comment]
I found the glitch on the V0.54 (new interface) where it can happen that a task with multiple entries gets - desynchronized.

The issue is that the "group" entry is not getting changed.
Need to investigate in detail, when this happens.

**Comment by Cyclodex** [comment]
It could be that the issues happens if you modify the first entry of a group. It will maybe stay in the group because the "group" identification will not change. I will need to improve the group ID further for that case.

**Comment by Cyclodex** [comment]
Should be solved with the commit: [a49914](https://github.com/Cyclodex/cyclone/commit/a49914fa7c133671bb26dc68d5c5e255231c76b1)
