### ISSUE TITLE
Manual time entry as first element of the list should calculate several durations of its own and the next element

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/cyclone#6]
If you add a manual time entry, which will be placed as first element in the list (like an early time entry at 6:00 or similar) will not calculate
- its own duration (since 00:00)
- the next entries duration is also missing

**Comment by pfiaux** [comment]
I think that's because there's an implicit start of the day but it's hidden:

```
$scope.lastEntryTimestamp = lastEntryTimestamp; // So the first entry works
```

Works but what if you reload the page? The other issue is that this value is never shown and you can't change it so it can be confusing the first time you use the tool (changing it would also mean updating the first entry).

One solution would be a `startOfDay` variable (which you would use for the first entry) and save.
- If startOfDay can't be loaded, set it and save it (first time use)
- If startOfDay isn't on the same day (yesterday) then set start of day again (using now)

Then next improvement would be displaying and allowing the user to edit start of day. Then you could set the start and add some early manual entries (if manual entry is before first entry but after start of day).

Another solution would be to allow editing of the start + end time of time entries.

If every entries have a start and end you could remove duration and use a class/function to always calculate the duration of an entry then you wouldn't need to update them.

**Comment by Cyclodex** [comment]
Oops, I think the first entry is now not using its own duration, I probably overwrite it because of "if it is the first entry".
This means, the first entry of your day, will not have the start and duration when your application booted in the morning.

Will have to fix this!

**Comment by davidsandoz** [comment]
Yep, I just realized that as well!

**Comment by Cyclodex** [comment]
As a workaround to fix the first "duration", please add a manual time entry:
Take the time you **checked in** , or whatever you think you started working.

It will then update your duration of the first (now second) entry.

If a **manual entry** is the first, it will always be **0min duration** as of now. (we could also take the time since 00:00, but I don't think this would be useful.
