### ISSUE TITLE
Automatically switch to the new day

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#61]
Currently, when we load the app on a new day, it is still on the day we last used it.

I suggest that if we load the app for the first time on a new day, it automatically switch to this new day (same behavior as in versions <=0.50).

**Comment by Cyclodex** [comment]
I tried this within #52 however the browsers are doing strange things when the tab is open for long time, or when you re-open the laptop etc. So its really not that easy as it sounds.

That was also why it was jumping to your "time" view over and over again.
I don't know yet how to solve this easily, please use the day-switcher for now when you start a new day. Or go to the welcome screen and click the navigation items to get to the current date.

If someone has ideas how to solve this without messing with the browser reloads, open for inputs.

Also note: Before 0.50 there were also issues with some users, that the data was not correct, so it is a more tricky part to really know about the right date, especially because the user can go to a different date manually as well.

**Comment by Cyclodex** [comment]
Interesting finding, even when my macbook is closed, it still seems to randomly execute the 1min timer and so runs the cyclone still in the background, this now leaded to a time entry at 00:17 for starting the day.

Not sure why but the scenario on the old cyclone was actually better, because it was redirected when I opened the macbook again. Will need to dig deeper into that, or solve the auto creation differently.

![screen shot 2017-10-26 at 07 58 24](https://user-images.githubusercontent.com/840929/32037212-7d435f68-ba24-11e7-9b17-eac3a4fc98fe.png)

**Comment by Cyclodex** [comment]
Working on this, decided that Cyclone will show a "Good morning" message and asking for when you started today.

I need to cover the following tasks:

- [x] Switch date automatically
- [x] Recognize multiple loadings, in case the laptop is "night active" (while being closed)
- [x] Suggest the latest visit as the "Starting the day" entry
- [x] Enable user to optionally select an other time from earlier visits (this might help if you start work and forget to visit cyclone - however without guarantee)
- [x] Enable user to optionally enter time manually
- [x] Add the correct entry depending on what the user wanted

**Comment by Cyclodex** [comment]
New version released. This is enough for the moment.
