### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by renestalder** [Cyclodex/cyclone#75]
That's only a small input. Would possibly like to fork your project but there is no LICENSE file at the moment. Would be great if you can add one at some point so we know what we're allowed to do and what not.

**Comment by Cyclodex** [comment]
_Hey, are you still using it? I thought you are not :)_

I will check the license thing, but what are your plans, you want to contribute something? (Wondering)
Don't forget that this was my code base for learning AngularJS and might be not the best base or solution for you. But I am open to changes, improvements & ideas you have. Please share them.

I will read into the license, but you should be fine and free to extend it as long as you share the code back and don't sell it. I will check which license is the best for this idea.

**Comment by Cyclodex** [comment]
Checked this mess of licenses to open up Cyclone, instead of keeping the GitHub defaults:
> You have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

And I think I will go with the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/).
This because I want that changes to it have to be contributed/shared and stay available to all people.

@renestalder what do you think, would this solve your problem? I am open for discussion depending on what your needs are.

See #76

**Comment by Cyclodex** [comment]
Looks like this is fine. Closing ticket.

**Comment by renestalder** [comment]
Seems like my e-mail reply in November never made it back to Github. Anyway, that's fine with GPLv3. I'm not the master of licenses, so cannot say exactly what limitations it will have. But at least that now allows everyone to fork your project. Thanks.
