### ISSUE TITLE
Marking a task as done with the keyboard doesn't trigger moving it in "Done"

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#77]
If you navigate on Cyclone with the keyboard up to a checkbox and hit space or enter to check it, the checkbox gets checked, but the task is not moved in the "Done" section and the time is not copied in the clipboard.

I suppose that the event listener is only on `click` and not on `change`.

**Comment by Cyclodex** [comment]
Thanks for reporting, will check it.

**Comment by Cyclodex** [comment]
Sometimes I hate those small details.

1. The clipboard feature doesn't work with the keyboard when using on the template. So I went the `ng-change` way.
1. The next problem was, that using the clipboard feature looses the focus
1. To fix this I had to implement a workaround, because `ng-change` doesn't work with `$event` to know the just used element.

I will test a little bit more, and then merge the pull request soon.
I hope it still works in all the browsers as before.

Please follow the pull request #79 , to know when it will be live.
