### ISSUE TITLE
Don't count private time in total time

### ISSUE THREAD

**Issue by davidsandoz** [Cyclodex/cyclone#9]
I would be interested in having my total work time of the day (to know if I worked enough or not).

Currently, the total time also counts the private time. Could we consider removing the private time from the total time? Or there could also be a _Total work time_ in addition to the total time.

**Comment by Cyclodex** [comment]
True,  or should we rethink the 'break' Projekt Name feature? Perhaps we should only not count  the private time instand of the breaks.

Anyway still unclear about the private/work switch...
Would it make more sense to say break/work. 

Or do we want to count private + work Hours separately and in addition having breaks for both of them... Hmmm. 
Any Inputs @pfiaux

**Comment by pfiaux** [comment]
"break" seems to be more of a special key word for project which allows to auto select private.

However since you have the option to set anything to private manually, I think it makes sense to filter by private and non private time for the total work.

I was looking at the code i'm not sure what `obj["break"] = true;` is for since we already have the type. You could easily only add the entires only if  `obj["type"] == 'work'`.

I think showing the total for work and the total for private would make it more clear.

The name of projects of work type doesn't do anything except group them so it's strange that if the name of private items is break it does something special.

**Comment by Cyclodex** [comment]
True, I will change this.
The feature was introduced very quickly and late. Thought I did not think very far ;)

Thanks for the feedback! Will be changed soon.

**Comment by Cyclodex** [comment]
I made a straight forward suggestion how we could display it.
Deployed it so you can already test it live!

![screen shot 2016-08-17 at 23 46 41](https://cloud.githubusercontent.com/assets/840929/17754681/fc5c4fee-64d5-11e6-98df-915c8673d3dc.png)

**Comment by Cyclodex** [comment]
I mark this as solved, if you have some other feedback , lets create new tickets. Thanks and have fun using it!
